services:
  ipmonitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipmonitor:1.0.0
    container_name: ipmonitor
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ipmonitor-data:/var/softwaresTCE/dados/ipmonitor
    networks:
      - docker_deploy_network

volumes:
  ipmonitor-data:
    name: ipmonitor-data

networks:
  docker_deploy_network:
    external: true
