services:
  ipmonitor:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipmonitor:1.0.0
    container_name: ipmonitor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ipmonitor-data:/var/softwaresTCE/dados/ipmonitor

volumes:
  ipmonitor-data:
    name: ipmonitor-data
